---
- name: Listar nodos y VMs desde Proxmox vía API REST
  hosts: localhost
  gather_facts: no
  vars:
    api_host: "https://192.168.3.6:8006"
    api_token_id: "admintst@pam!mytokenid"
    api_token_secret: "ca6d23ae-161a-4236-87f7-0e0a2ce7e506"
    headers:
      Authorization: "PVEAPIToken={{ api_token_id }}={{ api_token_secret }}"
      Content-Type: "application/json"
  tasks:

    - name: Obtener lista de nodos en Proxmox
      uri:
        url: "{{ api_host }}/api2/json/nodes"
        method: GET
        headers: "{{ headers }}"
        validate_certs: no
      register: nodos

    - name: Mostrar nodos encontrados
      debug:
        msg: "{{ nodos.json.data | map(attribute='node') | list }}"

    - name: Obtener VMs de cada nodo
      uri:
        url: "{{ api_host }}/api2/json/nodes/{{ item.node }}/qemu"
        method: GET
        headers: "{{ headers }}"
        validate_certs: no
      loop: "{{ nodos.json.data }}"
      loop_control:
        label: "{{ item.node }}"
      register: vms_por_nodo

    - name: Mostrar VMs por nodo
      debug:
        msg: >
          Nodo {{ item.item.node }}:
          {{ item.json.data | map(attribute='name') | list }}
      loop: "{{ vms_por_nodo.results }}"
