- name: Consultar VMs desde Proxmox
  hosts: localhost
  gather_facts: false

  vars:
    api_url: "https://192.168.3.6:8006"
    api_user: "{{ proxmox_user }}"
    api_pass: "{{ proxmox_password }}"

  tasks:
    - name: Obtener lista de VMs
      uri:
        url: "{{ api_url }}/api2/json/nodes/pve/qemu"
        method: GET
        user: "{{ api_user }}"
        password: "{{ api_pass }}"
        validate_certs: no
        force_basic_auth: yes
        return_content: yes
      register: vm_list

    - debug:
        var: vm_list.json.data
